import type { Metadata } from "next"
import "@workspace/ui/styles/globals.css"
import { fontVariables } from "@workspace/ui/lib/fonts"
import { cn } from "@workspace/ui/lib/utils"
import { AppProvider } from "@workspace/ui/components/app-provider"

export const metadata: Metadata = {
  title: "Personal Blog",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full overflow-y-auto scroll-smooth" suppressHydrationWarning>
      <body
        className={cn(
          fontVariables,
          "font-sans antialiased w-full bg-background overflow-x-hidden"
        )}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  )
}
