import type { Metadata } from "next"
import "@workspace/ui/styles/globals.css"
import { fontVariables } from "@workspace/ui/lib/fonts"
import { cn } from "@workspace/ui/lib/utils"
import { AppProvider } from "@workspace/ui/components/app-provider"
import { ProgressiveBlur } from "@workspace/ui/components/progressive-blur"
import { AppHeader } from "@workspace/ui/components/apps/portfolio/app-header"
import { AppFooter } from "@workspace/ui/components/apps/portfolio/app-footer"

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className="h-full overflow-y-auto scroll-smooth"
      suppressHydrationWarning
    >
      <body className={cn(fontVariables)}>
        <AppProvider>
          <AppHeader />
          <main id="layout-main" className="w-full max-w-4xl mx-auto bg-transparent">
            {children}
          </main>
          <ProgressiveBlur position="top" height="32px" />
          <ProgressiveBlur height="40px" />
          <AppFooter />
        </AppProvider>
      </body>
    </html>
  )
}
